import Head from 'next/head';
import Header from '../components/Header';
import Image from 'next/image';
import { MicrophoneIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/solid';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google v3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*HEADER*/}
      <Header />

      {/*BODY*/}
      <form className="flex flex-col items-center mt-40">
        <Image
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1280px-Google_2015_logo.svg.png"
          alt="logo"
          width="300"
          height="100"
          objectFit="cover"
        />
        <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 text-gray-500 mr-3" />
          <input type="text" className="flex-grow focus:outline-none" />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col sm:flex-row w-1/2 space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
          <button className="btn">Google search</button>
          <button className="btn">I`m Feeling Lucky</button>
        </div>
      </form>

      {/*FOOTER*/}
      <Footer />
    </>
  );
}
